"""
Scikit-learn baseline models for apogee prediction.

All models are wrapped in sklearn Pipelines (with StandardScaler) or
constructed as standalone estimators.  The FEATURE_COLS and TARGET_COL
constants must match the dataset generated by physics/simulation.py.

Included baselines
------------------
ridge           — Ridge regression (linear baseline, must-have)
decision_tree   — Decision Tree Regressor (interpretable baseline)
extra_trees     — Extra Trees Regressor (fast ensemble)
adaboost        — AdaBoost Regressor (boosting baseline)
lightgbm        — LightGBM Regressor (strong GBDT benchmark)
catboost        — CatBoost Regressor (strong GBDT benchmark)
"""
from __future__ import annotations

from pathlib import Path
from typing import Any

import joblib
import numpy as np
from sklearn.ensemble import AdaBoostRegressor, ExtraTreesRegressor
from sklearn.linear_model import Ridge
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeRegressor

import lightgbm as lgb
from catboost import CatBoostRegressor

# ── Feature / target specification ───────────────────────────────────────────

FEATURE_COLS: list[str] = [
    "h", "v", "a", "deployment", "rho",
    "t_since_burnout", "mass_dry", "A_ref", "Cd_total",
]
TARGET_COL: str = "target_apogee"


# ── Model builders ────────────────────────────────────────────────────────────

def build_ridge(alpha: float = 100.0) -> Pipeline:
    """Linear baseline with L2 regularisation."""
    return Pipeline([
        ("scaler", StandardScaler()),
        ("model", Ridge(alpha=alpha)),
    ])


def build_decision_tree(max_depth: int = 8, min_samples_leaf: int = 20) -> Pipeline:
    """Single decision tree — interpretable, fast, limited capacity."""
    return Pipeline([
        ("scaler", StandardScaler()),
        ("model", DecisionTreeRegressor(
            max_depth=max_depth,
            min_samples_leaf=min_samples_leaf,
            random_state=42,
        )),
    ])


def build_extra_trees(
    n_estimators: int = 300,
    max_features: float = 0.8,
) -> Pipeline:
    """Extra-randomised trees — fast, robust ensemble baseline."""
    return Pipeline([
        ("scaler", StandardScaler()),
        ("model", ExtraTreesRegressor(
            n_estimators=n_estimators,
            max_features=max_features,
            n_jobs=-1,
            random_state=42,
        )),
    ])


def build_adaboost(
    n_estimators: int = 200,
    learning_rate: float = 0.05,
) -> Pipeline:
    """AdaBoost over shallow decision trees."""
    return Pipeline([
        ("scaler", StandardScaler()),
        ("model", AdaBoostRegressor(
            estimator=DecisionTreeRegressor(max_depth=4),
            n_estimators=n_estimators,
            learning_rate=learning_rate,
            random_state=42,
        )),
    ])


def build_lightgbm(
    n_estimators: int = 600,
    learning_rate: float = 0.03,
    num_leaves: int = 63,
) -> lgb.LGBMRegressor:
    """LightGBM — fast GBDT, top tabular benchmark."""
    return lgb.LGBMRegressor(
        n_estimators=n_estimators,
        learning_rate=learning_rate,
        num_leaves=num_leaves,
        max_depth=-1,
        min_child_samples=20,
        subsample=0.8,
        colsample_bytree=0.8,
        reg_alpha=0.1,
        reg_lambda=1.0,
        n_jobs=-1,
        random_state=42,
        verbose=-1,
    )


def build_catboost(
    iterations: int = 600,
    learning_rate: float = 0.03,
    depth: int = 6,
    use_gpu: bool = False,
) -> CatBoostRegressor:
    """CatBoost — strong GBDT benchmark with minimal tuning."""
    return CatBoostRegressor(
        iterations=iterations,
        learning_rate=learning_rate,
        depth=depth,
        l2_leaf_reg=3.0,
        subsample=0.8,
        loss_function="RMSE",
        eval_metric="RMSE",
        task_type="GPU" if use_gpu else "CPU",
        random_seed=42,
        verbose=False,
    )


#: Registry of all available baseline builders
ALL_BASELINES: dict[str, Any] = {
    "ridge": build_ridge,
    "decision_tree": build_decision_tree,
    "extra_trees": build_extra_trees,
    "adaboost": build_adaboost,
    "lightgbm": build_lightgbm,
    "catboost": build_catboost,
}


# ── Persistence helpers ───────────────────────────────────────────────────────

def save_model(model: Any, path: Path) -> None:
    """Serialise a fitted model to *path* using joblib."""
    path.parent.mkdir(parents=True, exist_ok=True)
    joblib.dump(model, path)
    print(f"  Saved  {path}")


def load_model(path: Path) -> Any:
    """Load a previously saved model from *path*."""
    return joblib.load(path)
